apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: edge-system

resources:
  - namespace.yaml
  - ingress-gost-configmap.yaml
  - ingress-gost-daemonset.yaml
  - egress-singbox-daemonset.yaml
  - subscription-server-daemonset.yaml
