modules:
  http_2xx:
    prober: http
    timeout: 5s
    http:
      preferred_ip_protocol: ip4
      ip_protocol_fallback: false
      follow_redirects: true
  http_ingress_entry:
    prober: http
    timeout: 5s
    http:
      preferred_ip_protocol: ip4
      ip_protocol_fallback: false
      follow_redirects: true
      valid_status_codes: [200, 301, 302, 307, 308, 404]
  https_ingress_entry:
    prober: http
    timeout: 5s
    http:
      preferred_ip_protocol: ip4
      ip_protocol_fallback: false
      follow_redirects: true
      valid_status_codes: [200, 301, 302, 307, 308, 404]
      tls_config:
        insecure_skip_verify: true
  https_apiserver_livez:
    prober: http
    timeout: 5s
    http:
      preferred_ip_protocol: ip4
      ip_protocol_fallback: false
      follow_redirects: true
      valid_status_codes: [200, 401]
      tls_config:
        insecure_skip_verify: true
  tcp_connect:
    prober: tcp
    timeout: 5s
    tcp:
      preferred_ip_protocol: ip4
  icmp_ipv4:
    prober: icmp
    timeout: 5s
    icmp:
      preferred_ip_protocol: ip4
