apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: ghostfolio-redirect-to-oidc
  namespace: ghostfolio
spec:
  redirectRegex:
    regex: "^https?://[^/]+/ghostfolio/?$"
    replacement: "/ghostfolio/api/auth/oidc"
    permanent: false
