apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghostfolio-redis
  namespace: ghostfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ghostfolio-redis
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ghostfolio-redis
    spec:
      nodeSelector:
        region: sg
      containers:
        - name: redis
          image: redis:7-alpine
          args:
            - --requirepass
            - $(REDIS_PASSWORD)
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ghostfolio-redis-secrets
                  key: redis-password
          ports:
            - containerPort: 6379
              name: redis
          resources:
            requests:
              cpu: 20m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 256Mi
