apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - finbrain-configmap.yaml
  - finbrain-uploads-pvc.yaml
  - finbrain-deployment.yaml
  - finbrain-service.yaml
  - finbrain-forwardauth-middleware.yaml
  - finbrain-httproute.yaml
  - finbrain-networkpolicy.yaml
  - finbrain-db-backup-cronjob.yaml
