{{- $cert := .Files.Get .Values.tls.certFile | required (printf "missing certificate file %s" .Values.tls.certFile) -}}
{{- $key := .Files.Get .Values.tls.keyFile | required (printf "missing private key file %s" .Values.tls.keyFile) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.tls.secretName | quote }}
  labels:
    {{- include "traefik-public-gateway.labels" . | nindent 4 }}
  annotations:
    homelab.panda/certificate-common-name: {{ .Values.tls.certificate.commonName | quote }}
    homelab.panda/certificate-dns-names: {{ join "," .Values.tls.certificate.dnsNames | quote }}
    homelab.panda/certificate-issuer: {{ .Values.tls.certificate.issuer | quote }}
    homelab.panda/certificate-not-before: {{ .Values.tls.certificate.notBefore | quote }}
    homelab.panda/certificate-not-after: {{ .Values.tls.certificate.notAfter | quote }}
    homelab.panda/certificate-not-after-display: {{ .Values.tls.certificate.notAfterDisplay | quote }}
    homelab.panda/certificate-not-after-timezone: {{ .Values.tls.certificate.notAfterTimezone | quote }}
    homelab.panda/certificate-not-after-utc: {{ .Values.tls.certificate.notAfterUTC | quote }}
    homelab.panda/certificate-fingerprint-sha256: {{ .Values.tls.certificate.fingerprintSHA256 | quote }}
type: kubernetes.io/tls
stringData:
  tls.crt: |
    {{- $cert | nindent 4 }}
  tls.key: |
    {{- $key | nindent 4 }}
