apiVersion: v1
kind: ConfigMap
metadata:
  name: firefly-config
  namespace: firefly
data:
  TZ: Asia/Shanghai
  APP_ENV: production
  APP_DEBUG: "false"
  APP_URL: https://106.55.163.135/firefly/
  DB_CONNECTION: pgsql
  DB_HOST: postgresql.data.svc.cluster.local
  DB_PORT: "5432"
  DB_DATABASE: firefly
  AUTHENTICATION_GUARD: remote_user_guard
  TRUSTED_PROXIES: "**"
