apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - firefly-configmap.yaml
  - firefly-deployment.yaml
  - firefly-service.yaml
  - firefly-strip-prefix-middleware.yaml
  - firefly-strip-auth-headers-middleware.yaml
  - firefly-forwardauth-middleware.yaml
  - firefly-httproute.yaml
  - firefly-networkpolicy.yaml
