apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: edge-gateway-probe-exporter-script
    files:
      - edge_gateway_probe_exporter.py

resources:
  - edge-gateway.yaml
